export {
  configureGlobalQuickNoteShortcut,
  createVaultEntry,
  configureGlobalRevealShortcut,
  deleteVaultEntry,
  importEditorAsset,
  importEditorAssetFromPath,
  hideMainWindowToTray,
  initVault,
  openQuickNoteWindow,
  openExternalTarget,
  readInitialOpenFile,
  readLocalAssetDataUrl,
  readMarkdownFile,
  readVaultDirectory,
  readVaultIndexFiles,
  searchVaultTagFiles,
  renameVaultEntry,
  revealWindow,
  writeExportFile,
  writeMarkdownFile,
  writeVaultWorkspaceState,
} from "../fs/tauriFs";

export type { QuickNoteInitialSurface } from "../fs/tauriFs";
